### ISSUE TITLE
Why does FM_p2p not use multiplication with the area matrix of mesh1?

### ISSUE THREAD

**Issue by JunzheJosephZhu** [RobinMagnet/pyFM#17]
k2, k1 = FM_12.shape

    assert k1 <= evects1.shape[1], \
        f'At least {k1} should be provided, here only {evects1.shape[1]} are given'
    assert k2 <= evects2.shape[1], \
        f'At least {k2} should be provided, here only {evects2.shape[1]} are given'

    if use_adj:
        emb1 = evects1[:, :k1] # [n1, k1]
        emb2 = evects2[:, :k2] @ FM_12 # [n2, k1]

    else:
        emb1 = evects1[:, :k1] @ FM_12.T # [n1, k2]
        emb2 = evects2[:, :k2] # [n2, k2]

    p2p_21 = knn_query(emb1, emb2,  k=1, n_jobs=n_jobs)

It seems counterintuitive that the area matrix of the first mesh is not in the multiplicaiton, since both descriptors are projected with self.eigenvectors.T @ (self.A @ func), and then C is computed.

Therefore, shouldnt mapping an indicator function from mesh1 to mesh 2 look like evects2 @ FM_12 @ evects1.T @ A1 @ np.eye(n1)?

In the KNN case, shouldn't we do knn_query(evects2.T @ A2 @ np.eye(n2), FM_12 @ evects1.T @ A1@ np.eye(n1))?

**Comment by RobinMagnet** [comment]
Hi,

In order to find the pointwise map from a functional map, we are typically minimizing the following energy:
$$\Pi_{21}^* = \min_{\Pi_{21}} \|\| \Pi_{21} \Phi_1 - \Phi_2 C_{12}\|\|_{L^2(S_2)}^2 $$

Note that this uses the $L^2$ norm on shape $S_2$, where $\|\|f\|\|_{L^2(S_2)}^2 = f^\top A_2 f$ with $A_2$ the diagonal area matrix of shape $S_2$.

Since matrix $A_2$ is diagonal, we can solve independently for each line of $\Pi_{21}$, where line $i$ only consists in zeros except at the index of the corresponding point in shape $S_1$.

For the $i$-th line, this would mean we seek $$\text{NNQuery}_j([A_2]_i [\Phi_1]_i, [A_2]_i [\Phi_2 C_12]_j )$$, but we can drop the $[A_2]_i $.

Hope this is clear enough

**Comment by JunzheJosephZhu** [comment]
So $\Phi_2 C_{12}^\top$ would be the operator that maps functions in the spectral space of mesh1 to mesh2's manifold, and $\Pi_{21} \Phi_1$ would consist of first mapping functions from the spectral space of mesh1 to mesh1's manifold, then using a transport matrix $\Pi_{21}$ to map it to mesh2's manifold. Is my understanding correct?

**Comment by RobinMagnet** [comment]
Sorry, there was a typo in my previous answer.

Actually, we here compare:
- $\Pi_{21} \Phi_1$, which takes a function in the LBO subspace on shape $S_1$, takes it back to the hat basis on $S_1$ then transfers to the hat basis on $S_2$ using the pointwise map
- $\Phi_2 C_{12}$ which takes a function in the LBO subspace on shape $S_1$, transfers the the LBO subspace on $S_2$ using the functional map and takes it back to the hat basis on $S_2$.


This is what we call the "adjoint" solution, and you can find details about it [here](https://openaccess.thecvf.com/content/CVPR2021/html/Pai_Fast_Sinkhorn_Filters_Using_Matrix_Scaling_for_Non-Rigid_Shape_Correspondence_CVPR_2021_paper.html).

The more standard method presented in the [original paper](https://people.csail.mit.edu/jsolomon/assets/fmaps.pdf) instead compares:
- $\Phi_1 C_{12}^\top$, which is easier read as $C_{12} \Phi_1^\top$, and is just transferring *per-vertex embeddings* from shape $S_1$ to $S_2$. Per vertex embeddings are *rows* of $\Phi_1\in\mathbb{R}^{n_1\times k_1}$.
- $\Phi_2$ which are per-vertex embeddings on shape $S_2$. NN query allows to minimize this.

The interpretation for each method is actually different since it's a bit hard to provide a good explanation of what $C_{12}^\top$ is as an operator.

**Comment by JunzheJosephZhu** [comment]
Thanks! Since the mapping matrix is not guarenteed to be orthonormal, your method seems to be more robust in cases where the two meshes have vastly different numbers of vertices and area.
In the standard method you outlined here, I dont see an area matrix being used to project indicator functions onto LBO basis. Is this because we're not assuming it's a hat function, but just a Kronecker delta function here?

By the way, I'm really amazed by how much you know about all this. I'm leading a robotics-related project that trains visual foundation models to produce features for shap matching. I sent you an email with some questions, would really appreciate it if we could have a brief meeting!
