### ISSUE TITLE
no setup.py

### ISSUE THREAD

**Issue by renaudgaucher** [RobinMagnet/pyFM#3]
Hello Robin, 
May you add a setup.py file in order to make the package installable with python tools ? Thanks !

**Comment by jo-mueller** [comment]
@RobinMagnet do you still maintain this? If so, I could add some stuff to the repo to make it pip installable.

**Comment by RobinMagnet** [comment]
Hi @jo-mueller, I do still use this package for all my experiments. My own branch has some differences with this one but all features are already there. 

There is not much to add right now, except Discrete Optimization which is very hard to transform into readable code, and Reversible Harmonic Maps which will certainly be part of another repository since they don't use functional maps.

I've been refraining from making it pip installable because I was afraid too many bugs were still hiding in the code so I wanted people to think about pulling changes. But it seems to be quite stable now.

Thanks for the PR ! #5
